export const POST_LOGIN = 'POST_LOGIN';
export const DID_LOGIN_ACTION = 'DID_LOGIN_ACTION';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const LOG_OUT = 'LOG_OUT';

export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const REMOVE_ALL_FROM_CART = 'REMOVE_ALL_FROM_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';

export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAIL = 'GET_USER_INFO_FAIL';

export const GET_CATEGORY_INFO = 'GET_CATEGORY_INFO';
export const GET_CATEGORY_INFO_SUCCESS = 'GET_CATEGORY_INFO_SUCESS';
export const GET_CATEGORY_INFO_FAIL = 'GET_CATEGORY_INFO_FAIL';

export const GET_USER_FAVORITE = 'GET_USER_FAVORITE';
export const GET_USER_FAVORITE_SUCCESS = 'GET_USER_FAVORITE_SUCCESS';
export const GET_USER_FAVORITE_FAIL = 'GET_USER_FAVORITE_FAIL';

export const SET_USER_FAVORITE = 'SET_USER_FAVORITE';
export const SET_USER_FAVORITE_SUCCESS = 'SET_USER_FAVORITE_SUCCESS';
export const SET_USER_FAVORITE_FAIL = 'SET_USER_FAVORITE_FAIL';

export const REMOVE_USER_FAVORITE = 'REMOVE_USER_FAVORITE';
export const REMOVE_USER_FAVORITE_SUCCESS = 'REMOVE_USER_FAVORITE_SUCCESS';
export const REMOVE_USER_FAVORITE_FAIL = 'REMOVE_USER_FAVORITE_FAIL';

export const ADD_ORDER = 'ADD_ORDER';
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS';
export const ADD_ORDER_FAIL = 'ADD_ORDER_FAIL';